CC = gcc
CFLAGS = -Iinclude
LIBS = -lfreeglut -lopengl32 -lglu32 -lgdi32
TARGET = main.exe
SRC = main.c input.c render.c chunks.c chunkLoaderManager.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(SRC) -o $(TARGET) $(CFLAGS) $(LIBS)

clean:
	del $(TARGET)